# Generated by Django 3.0.5 on 2022-06-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('questionSetDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.AutoField(primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=200)),
                ('sectionDescription', models.TextField()),
                ('sectionSetDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('surveyID', models.AutoField(primary_key=True, serialize=False)),
                ('surveyName', models.CharField(max_length=200)),
                ('surveyDescription', models.TextField()),
                ('surveySetDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('surveyQuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('surveyQuestionAttribute', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acx.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acx.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acx.Section'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(through='acx.SurveyQuestion', to='acx.Survey'),
        ),
    ]
