# Generated by Django 3.0.5 on 2022-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0007_auto_20220616_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subSection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.CharField(max_length=255),
        ),
    ]
