# Generated by Django 3.0.5 on 2022-06-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0008_auto_20220616_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subSection',
        ),
    ]
