# Generated by Django 3.0.5 on 2022-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0010_auto_20220616_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSection',
        ),
    ]
