# Generated by Django 3.0.5 on 2022-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0012_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='acx.Survey'),
        ),
    ]
