# Generated by Django 3.0.5 on 2022-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0014_auto_20220616_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'section')},
        ),
    ]
