# Generated by Django 3.0.5 on 2022-09-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0016_surveyquestion_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=200)),
                ('joinDate', models.DateTimeField(verbose_name='Join Date')),
                ('streamSize', models.IntegerField(default=1)),
                ('projectStatus', models.IntegerField(choices=[(0, 'BDDING STAGE'), (2, 'FOLLOW-UP'), (3, 'WAITING FOR ANSWER'), (4, 'CLOSED'), (5, 'COMPLETED'), (6, 'WON')], default=0)),
                ('description', models.TextField()),
                ('officialEmail', models.EmailField(max_length=254)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acx.Client'),
        ),
    ]
