# Generated by Django 3.0.5 on 2022-09-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acx', '0017_auto_20220905_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acx.Client'),
        ),
    ]
